### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by JuiP**

### CODE REVIEW

**Comment by JuiP** [comment]
@walterbender Please review and merge.
Readme isn't that great but something better than nothing?
Thanks :)

**Comment by walterbender** [comment]
Maybe a screenshot? and a brief explanation of how to play?

**Comment by JuiP** [comment]
Done :)

**Comment by ayushnawal** [comment]
@quozl, I guess we can merge this 

@JuiP Thanks for the pull request

**Pull request merged**
